apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: payments-api-scaler
  namespace: prod
  labels:
    app.kubernetes.io/name: payments-api
  annotations:
    pcap.io/owner: "payments-team"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payments-api
  pollingInterval: 15
  cooldownPeriod: 60
  minReplicaCount: 2
  maxReplicaCount: 25
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: "kafka-bootstrap.kafka.svc:9092"
        consumerGroup: "payments-api"
        topic: "payments"
        lagThreshold: "100"
        offsetResetPolicy: "latest"
