apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
commonLabels:
  app.kubernetes.io/name: payments-api
  app.kubernetes.io/part-of: kairos-demo
resources:
  - ../../manifests/deployment.yaml
  - ../../manifests/scaledobject.yaml
