"""Render the PR title + body from a ScalingDecision + LLMAdvice."""

from __future__ import annotations

from jinja2 import Environment, select_autoescape

from pcap.domain.models import LLMAdvice, ScalingDecision

_env = Environment(
    autoescape=select_autoescape(default=False, default_for_string=False),
    trim_blocks=True,
    lstrip_blocks=True,
)

_BODY_TEMPLATE = _env.from_string(
    """\
## Summary

**Action:** `{{ decision.action.value }}`
**Reason:** `{{ decision.reason_code }}`
**Severity:** `{{ decision.severity.value }}`
**Confidence:** {{ "%.2f"|format(decision.confidence) }}
**Correlation ID:** `{{ decision.correlation_id }}`

{{ decision.rationale }}

## Forecast

| Metric | Horizon | Model | P95 | Peak | Peak At |
|---|---|---|---|---|---|
{% for f in decision.forecasts -%}
| `{{ f.metric }}` | {{ f.horizon_hours }}h | {{ f.model_used.value }} | {{ "%.2f"|format(f.p95_predicted) }} | {{ "%.2f"|format(f.peak_predicted) }} | {{ f.peak_at.isoformat() }} |
{% endfor %}

## Proposed Change

{% if decision.target_replicas is not none -%}
- **Replicas:** {{ decision.workload.current_replicas }} → **{{ decision.target_replicas }}**
{% endif -%}
{% if decision.target_cpu_request -%}
- **CPU request:** {{ decision.workload.cpu_request }} → **{{ decision.target_cpu_request }}**
{% endif -%}
{% if decision.target_mem_request -%}
- **Memory request:** {{ decision.workload.mem_request }} → **{{ decision.target_mem_request }}**
{% endif %}

{% if advice %}
## Why this matters (LLM-generated)

_{{ advice.why }}_

**Horizontal vs vertical:** {{ advice.horizontal_vs_vertical }}

**Risk of inaction:** {{ advice.risks_of_inaction }}

### Engineer steps
{% for step in advice.engineer_steps -%}
- {{ step }}
{% endfor %}

### Validation steps
{% for step in advice.validation_steps -%}
- [ ] {{ step }}
{% endfor %}

_Advice generated by {{ advice.provider_used.value }} (prompt version {{ advice.prompt_version }}, {{ advice.tokens_used }} tokens)._
{% endif %}

## Reviewer checklist

- [ ] Forecast looks reasonable on the Grafana dashboard
- [ ] Target values don't exceed quota / SKU budget
- [ ] No open incidents for `{{ decision.workload.uid }}`
- [ ] Proceed to merge or request changes

---

_Generated by [PCAP](https://github.com/your-org/pcap) — Predictive Capacity & Autoscaling Platform. Decision hash: `{{ decision_hash }}`._
"""
)


def render_pr_title(decision: ScalingDecision) -> str:
    w = decision.workload
    return f"[PCAP] Scale {w.kind.value}/{w.name} in {w.namespace}: {decision.action.value}"


def render_pr_body(decision: ScalingDecision, advice: LLMAdvice | None = None) -> str:
    return _BODY_TEMPLATE.render(
        decision=decision,
        advice=advice,
        decision_hash=decision.decision_hash(),
    )
